config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  get '/summary' => 'pages#summary'
  get '/education' => 'pages#education'
  get '/portfolio' => 'pages#portfolio'
  get '/software' => 'pages#software'
  get '/projects' => 'pages#projects'
  root 'pages#home'
  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
      @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]
      ContactMailer.contact_email(name, email, body).deliver
      flash[:success] = 'Message sent!'
      redirect_to new_contact_path
    else
      flash[:danger] = 'Error occured, message has not been sent.'
      redirect_to new_contact_path
    end
  end
  
  private
    def contact_params
      params.require(:contact).permit(:name, :email, :comments)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    
    def summary
    end
    
    def education
    end
    
    def portfolio
    end
    
    def projects
    end
    
    def software
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<div class="animated fadeIn">
  
  <div class="col-md-2"></div>
  
  <div id="contactform" class="col-md-8">
    <h3>Contact</h3>
  
    <%= form_for @contact do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :message %>
        <%= f.text_area :comments, class: 'form-control' %>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-default' %>
    <% end %>
  </div>

  <div class="col-md-2"></div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Josh Ludvigson</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Raleway:500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Raleway:600' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="animate.min.css">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link href='http://fonts.googleapis.com/css?family=Oswald:400,300' rel='stylesheet'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="headings">
    <div class="container">
      <div class="row">
        <h1><%= link_to "Josh Ludvigson", root_path %></h1>
        <h3><%= link_to "Piping Designer", root_path %> <span style="color: #9acd32;">|</span> <%= link_to "Drafter", root_path %></h3>
      </div>
    </div>
  </div>

  <div class="navigation">
    <div class="container">
      <div class="row">
        <div class="col-md-4 navleft">
          <ul dir="rtl" class="mymark">
            <li id="linka"><%= link_to "Summary", summary_path, :id => "sum" %></li>
            <li id="linkb"><%= link_to "Education", education_path, :id => "edu" %></li>
            <li id="linkc"><%= link_to "Software", software_path, :id => "sof" %></li>
          </ul>
        </div>
        <div class="col-md-4">
          <%= link_to(image_tag("mee.jpg", :class => "item", :alt => "home"), root_path, :id => "sum") %>
        </div>
        <div class="col-md-4 navright">
          <ul class="mymark">
            <li id="linka"><%= link_to "Projects", projects_path, :id => "pro" %></li>
            <li id="linkb"><%= link_to "Portfolio", portfolio_path, :id => "por" %></li>
            <li id="linkc"><%= link_to "Contact", new_contact_path, :id => "con" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="details">
    <div class="container">
      <div class="row">
        
        <!-- Create the DIV swapping content here -->
        <div class="content primary-content">
          <% flash.each do |key, value| %>
            <%= content_tag :div, value, class: "alert alert-#{key}" %>
          <% end %>
          
          <%= yield %>
          
        </div>
      </div>
    </div>
  </div>
          

  <div class="footer">
    <div class="container">
      <div class="row">
        <p><%= link_to "Home", root_path, :id => "sum" %> - <%= link_to "Summary", summary_path, :id => "sum" %> - <%= link_to "Education", education_path, :id => "edu" %> - <%= link_to "Software", software_path, :id => "sof" %> - <%= link_to "Projects", projects_path, :id => "pro" %> - <%= link_to "Portfolio", portfolio_path, :id => "por" %> - <%= link_to "Contact", new_contact_path, :id => "con" %></p>
        <div class="leftfoot"><a href="http://www.joshludvigson.me">www.joshludvigson.me</a>  
          <span class="links">   
            <a href="https://ca.linkedin.com/in/josh-ludvigson-a8240b34"><%= image_tag("linkedin.png", :class => "linkedinimg", :alt => "Josh Ludvigson") %></a>
          </span>
          <p style="color: rgba(255,255,255,.5);">&copy 2015 - Developed by Josh Ludvigson</p>
        </div>
      </div>
    </div>
  </div>
  
</body>
</html>

app/views/pages/education.html.erb
<div id="education" class="animated fadeIn">
    <h3>Educational Background</h3>
    <ul class="edulist">
      <li>Engineering Design and Drafting Technology Diploma w/ Honours</li>
      <li>Emergency First Aid, Level A (St. John Ambulance) – Expires 2017</li>
      <li>H2S Alive – Expires 2018</li>
      <li>WHMIS – Expires 2015</li>
    </ul>
</div>

app/views/pages/home.html.erb
<div id="home" class="animated fadeIn">
     <div class="col-md-2"></div>
     <div class="col-md-4 navright">
        <h3 style="text-align: center; font-weight: 400;">Design</h3>
        <ul class="edulist">
            <li>3D Modeling using intelligent modeling software (CADWorx)</li>
            <li>Plant Layout, Equipment Layout, Piping Layout</li>
            <li>Fabricated Package Design</li>
            <li>Interference and/or clash detection checks</li>
            <li>Line study</li>
            <li>Navisworks publishing</li>
            <li>C2 file generation (for Caesar stress analysis)</li>
            <li>Facility As-builds (field sketches / redline markups)</li>
            <li>Bill of Material (BOM)</li>
        </ul>
    </div>
    
    <!-- <div class="col-md-2"></div> -->
    
    <div class="col-md-4 navright">
        <h3 style="text-align: center; font-weight: 400;">Drafting</h3>
        <ul class="edulist">
            <li>2D and 3D drafting</li>
            <li>P&ID</li>
            <li>PFD</li>
            <li>GA</li>
            <li>Isometric</li>
            <li>Plot plan</li>
            <li>Key plan</li>
            <li>Mechanical detail drawing</li>
            <li>Re-drafting native drawings</li>
            <li>Man hour estimates</li>
            <li>Checking</li>
        </ul>
    </div>
    <div class="col-md-2"></div>
</div>

app/views/pages/portfolio.html.erb
<div id="portfolio" class="animated fadeIn">
    <h3>Portfolio</h3>
    <p>The portfolio section is currently under development, and will showcase custom renders and animations of projects I've worked on. Check in again soon...</p>
</div>

app/views/pages/projects.html.erb
<div id="projects" class="animated fadeIn">
    <h3>Project Highlights</h3>

    <div class="spacing">
        <h4 class="thick">Cutbank Gas Plant, Seven Generations Energy Ltd, Alberta:</h4>
        <p style="float: left;"><%= image_tag("ren6_75px.png", :class => "projimg", :alt => "Cutbank") %>
        <span class="big thick green">Piping Area Lead</span> <span class="green">(Liquids Handling and Storage Areas):</span>  This grassroots project involved the design of a sweet natural gas plant producing 250 MMSCFD of sweet natural gas, and 6000 bbl/d of sweet NGL.  Responsible for the liquids handling systems which involved NGL bullets, NGL transfer pumps, slop tanks, HC drain vessel, and LACT unit.  Responsibilities include overall layout and design, delegation of tasks, tracking and reporting, and checking of pile, structural, equipment, and piping mechanical packages.</p>
    </div><div style="clear: both;" class="bump"></div>

    <div class="spacing">
        <h4 class="thick">Super Pad 29, Seven Generations Energy Ltd, Alberta:</h4>
        <p style="float: left;"><%= image_tag("ren8_75px.png", :class => "projimg", :alt => "Super Pad 29") %>
        <span class="big thick green">Piping Area Lead</span> <span class="green">(Inlet Area):</span>  This project involved the design of a super pad capable of 50 MMSCFD of sales gas. Responsible for the design of the inlet riser area, inlet ESD/Blowdown area, as well as the pipeline riser sites feeding the plant inlet area.</p>
    </div><div style="clear: both;" class="bump"></div>

    <div class="spacing">
        <h4 class="thick">Simonette Gas Plant, Keyera Energy, British Columbia:</h4>
        <p style="float: left;"><%= image_tag("ren10_75px.png", :class => "projimg", :alt => "simonette") %>
        <span class="big thick green">Piping Area Lead</span> <span class="green">(Hot Oil Heater / Flare):</span>  This project involved the addition of condensate stabilization to a sour gas plant of 105 MMSCFD. Responsible for the design of the flare and hot oil heater areas, along with accompanying sub racks and main rack tie-ins.  Responsibilities include overall layout and design, delegation of tasks, and checking of pile, structural, equipment, and piping mechanical packages.</p>
    </div><div style="clear: both;" class="bump"></div>

    <div class="spacing">
        <h4 class="thick">Saturn 1, Shell Canada, N. E. British Columbia:</h4>
        <p style="float: left;"><%= image_tag("foxcreek4.png", :class => "projimg", :alt => "saturn") %>
        <span class="big thick green">Intermediate Piping Designer</span> <span class="green">(Sales, Power Gen, Rack Modules, VRU):</span>  Involved in the design of a 200 MMSCFD sweet natural gas processing plant in the Groundbirch area of British Columbia.  Design responsibilities included the sales gas building, fuel gas buy-back skid, power generation area, blowdown skid, modular pipe rack, and plant liquids metering skid.  I was also the primary drafter for the plot plan, and daily model publish.</p>
    </div><div style="clear: both;" class="bump"></div>
    
    <div class="spacing">
        <h4 class="thick">ARC Resources, Parkland Oil Processing & Solution Gas Plant</h4>
        <p style="float: left;"><%= image_tag("render4.png", :class => "projimg", :alt => "medicine hat") %>
        <span class="big thick green">Intermediate Piping Designer:</span>  This plant produced 128 MMSCFD of sweet natural gas, 9800 bbl/d of oil and 7000 bbl/d of NGL. General design duties included conceptual models, detail design, P&ID drafting, and valve library.</p>
    </div><div style="clear: both;" class="bump"></div>

    <div class="spacing">
        <h4 class="thick">Fox Creek Pump Station, Pembina, Alberta</h4>
        <p style="float: left;"><%= image_tag("render2.png", :class => "projimg", :alt => "fox creek pump stn") %>
        <span class="big thick green">Piping Designer:</span>  Drafting of P&ID’s and GA’s for the as-built and new construction phases of the project. This is a crude and NGL pumping station capable of switching between commodities to meet customer needs.</p>
    </div><div style="clear: both;" class="bump"></div>
    
    <div class="spacing">
        <h4 class="thick">Various Locations, Pengrowth Energy Corporation, Olds and Westward Ho, Alberta</h4>
        <p style="float: left;"><%= image_tag("ren12_75px.jpg", :class => "projimg", :alt => "pengrowth") %>
        <span class="big thick green">Piping Lead Designer:</span>  Overseeing the drafting and design of Pengrowth projects in Alberta. These projects include gas plant modifications (tank farms, VRU’s, separators, and compressors), pipeline tie-ins, wellsite tie-ins, and complete gas plant as-builds.  Drafting duties include P&ID’s, PFD’s, plot plans, isometrics, 3D models, BOM’s, line lists, and estimating.</p>
    </div><div style="clear: both;" class="bump"></div>
    
    <div class="spacing">
        <h4 class="thick">Various Locations, City of Medicine Hat, Alberta and Saskatchewan</h4>
        <p style="float: left;"><%= image_tag("ren11_75px.png", :class => "projimg", :alt => "medicine hat") %>
        <span class="big thick green">Piping Lead Designer:</span>  Overseeing the drafting and design of City of Medicine Hat projects in Alberta and Saskatchewan. These projects include gas plant modifications (compression, water injection, and separation), pipeline tie-ins, well tie-ins, overpressure protection, and MOC’s.  Drafting duties include field as-builds of riser sites and batteries, P&ID’s, PFD’s, plot plans, isometrics, 3D models, BOM’s, line lists, and estimating.</p>
    </div><div style="clear: both;" class="bump"></div>
</div>
<div style="clear: both;" class="bump"></div>

app/views/pages/software.html.erb
<div id="software" class="animated fadeIn">
    <h3>Software Expertise</h3>
    <p>I'm an <span class="green">expert user</span> of <span class="green">CADWorx</span>, <span class="green">AutoCAD</span>, and <span class="green">Navisworks</span> software for design and drafting work.  I have also used <span class="green">Inventor</span> professionally for mechanical design.</p>
    <p>I have used <span class="green">Excel</span> and <span class="green">Word</span> for over fifteen years, and I'm a seasoned pro in the windows environment.</p>
    <p>I have college level training with <span class="green">Civil 3D</span> and <span class="green">Revit</span>, and I could easily pick up where I left off.  Autodesk software is all very similiar, allowing for quick learning and recall, kind of like riding a bike...</p><div style="clear: both;" class="bump"></div>
</div>

app/views/pages/summary.html.erb
<div id="summary" class="animated fadeIn">
    <h3>Personal Summary</h3>
    <div class="spacing">
        <p>I'm a Piping Designer located in Calgary, Alberta with experience designing gas plants and SAGD facilities, and MOC work for oil and gas pipelines, batteries, and related facilities. I have solid field experience as-building risers, well sites, oil batteries, and gas plants.  Have a look through my <%= link_to "project", projects_path, :id => "pro" %> experience for more details, and check out <a href="https://ca.linkedin.com/in/josh-ludvigson-a8240b34" target="_blank">my profile on LinkedIn.</a></p>
    </div>
    <div class="spacing">
        <p>I hold an Engineering Design and Drafting Technology Diploma with Honours, and I have previous training in purchasing and operations management with PMAC and APICS.  I'm also a web design hobbiest, self-trained in order to launch my website and learn new skills.</p>
    </div>
    <div class="spacing">
        <p>As a Piping Designer my experience has seen me in leadership roles, running small projects independantly, or as an area lead on larger scale projects.  Quality, speed, and consistency are top priority with drafting, and my designs are customer focused on safety, operability, and cost.  I am actively contracting, and open to short-term and long-term contracts, as well as permanent full-time employment.  If you are looking for a hard working, skilled piping designer for your next project, you've come to the right place!  <%= link_to "Contact me!", new_contact_path, :id => "con" %></p>
    </div><div style="clear: both;" class="bump"></div>
</div>